load masks from colmap-style output directory in DensifyPointCloud
cdcseacave/openMVS pull request #1011
Opened 2023-06-19 22:43 UTC by dllu

Loads masks from an arbitrary folder.

2023-06-20 09:07 UTC, cdcseacave requested changes
nice, but instead of adding support for importing masks in each interface, why not use instead the `--mask-path <folder>` functionality already existing in DensifyPointcloud which does exactly this?

2023-06-23 04:47 UTC, 4CJ7T commented
colmap uses `image_name.image_extension.png` and --mask-path uses `image_name.mask.png`.
colmap doesn't undistort masks but can be scripted to. I hope `MAKE_PATH_REL` does what I think it does, if it does, awesome possum, it will be the bee's knees, maybe even the cat's meow.

2023-06-23 05:04 UTC, 4CJ7T commented
I think it's nice as well but since colmap doesn't natively undistort masks, the image extension can be renamed to `.mask.png` in a script to work with `--mask-path`.

2023-06-24 07:39 UTC, cdcseacave commented
if that is true (colmap does no undistort the masks as well) then this change make even less sense: even if imported in MVS they will be wrongly used; so the only way to make this happen is a script using colmap and the undistoreted scene params that undistorts the masks (as at the interface point the scene does not have this information anymore), and in the process can also make sure they follow the OpenMVS file naming

2026-09-12 00:49 UTC, cdcseacave commented
Thank you for the contribution. As noted in the review, mask support is already provided across OpenMVS applications (such as \DensifyPointCloud\ and \RefineMesh\) via the \--mask-path\ command line option. Closing this PR.

2026-09-12 00:49 UTC, closed without merging