pixi shell
cdcseacave/openMVS pull request #1169
Opened 2024-08-14 14:55 UTC by waqarsqureshi

Files to create pixi shell environment for openMVS without CUDA

2024-08-15 02:06 UTC, pmoulon commented on pixi.toml
> +binutils = ">=2.40,<3"
Do you know why you required this?

2024-08-15 02:06 UTC, pmoulon commented on pixi.toml
> +build = ">=0.7.0,<0.8"
Never got to need build before

2024-08-15 02:06 UTC, pmoulon commented on pixi.toml
> +
Please add task for getting igl and compile and eventually run the various binaries

2024-08-15 02:06 UTC, pmoulon commented on pixi.toml
> +[dependencies]
Maybe add git in the deps to checkout igl as a Pixi setup task

2024-08-22 14:37 UTC, cdcseacave requested changes

2024-08-22 14:37 UTC, cdcseacave commented on scripts/python/MvgMvsPipeline.py
> +OPENMVG_BIN = "/home/waqar/reconstruction/openMVG_build/Linux-x86_64-Release/" #whereis("openMVG_main_SfMInit_ImageListing")
pls do not hardcode this paths

2024-08-22 14:37 UTC, cdcseacave commented on scripts/python/readPly.py
> +#!/usr/bin/env python3
pls decribe what is this script for
is this needed by the current pixi shell build or can be put in a different PR?

2026-09-12 00:49 UTC, cdcseacave commented
Thank you for the submission. OpenMVS standardizes on CMake and vcpkg for cross-platform dependency management. This PR also includes personal hardcoded paths in \MvgMvsPipeline.py\ and a monolithic lockfile. Closing this PR.

2026-09-12 00:49 UTC, closed without merging