DensifyPointCloud: add --ignore-mask-path arg to easily specify mask images
cdcseacave/openMVS pull request #940
Opened 2023-02-16 03:03 UTC by kenshi84

2023-02-16 14:39 UTC, 4CJ7T commented
Don't think it should be called "ignore-mask-path", as it makes it sound the path is being ignored. "ignore-mask-label" is describing what it does but I guess a mask can also be called an ignore mask.

2023-02-17 00:10 UTC, kenshi84 commented
@4CJ7T 
Thanks for your feedback, I modified the patch acoordingly.

I chose that name because of the `--ignore-mask-label` arg name and function names `ApplyIgnoreMask` & `ImportIgnoreMask` in DepthMap.cpp which made me think that "ignore mask" is some special term in this context. But I agree, just simply using "mask" makes sense and should suffice.

2023-02-25 12:23 UTC, cdcseacave requested changes
LGTM, I will merge it after you point it to develop instead of master

2023-02-25 12:23 UTC, cdcseacave commented on apps/DensifyPointCloud/DensifyPointCloud.cpp
> +			image.maskName = Util::ensureFolderSlash(OPT::strMaskPath) + Util::getFileNameExt(image.name);
you could also add here a check that the composed mask file name actually exists

2023-03-14 05:55 UTC, kenshi84 commented
Rebased onto the `develop` branch, which made me aware of this patch https://github.com/cdcseacave/openMVS/commit/2874f19fbcdf3c4d7c3b98866b7d57f8129dac29 which offers a simple way to specify mask images. Given this patch, I decided to use the same file extension (`.mask.png`) to avoid chance of confusion by the user. Also added the file existence check.

2023-03-16 08:28 UTC, cdcseacave requested changes

2023-03-16 08:28 UTC, cdcseacave commented on apps/DensifyPointCloud/DensifyPointCloud.cpp
> +		if (OPTDENSE::nIgnoreMaskLabel < 0) {
this check is probably not needed, as all you do here is setting the maskName variable, which will not be used if not requested; however can be saved and added to the MVS scene file; what do you think?

2023-03-16 08:28 UTC, cdcseacave commented on apps/DensifyPointCloud/DensifyPointCloud.cpp
> +			image.maskName = Util::ensureFolderSlash(OPT::strMaskPath) + Util::getFileName(image.name) + ".mask.png";
Util::ensureFolderSlash(OPT::strMaskPath) needs to be run once at the beginning only; and you should use ensureValidFolderPath instead, which does more checks

2023-03-16 08:28 UTC, cdcseacave commented on apps/DensifyPointCloud/DensifyPointCloud.cpp
> +				VERBOSE("Mask image %s not found in %s", image.maskName.c_str(), OPT::strMaskPath.c_str());
do not print strMaskPath as that is included in the maskName now

2023-03-17 03:49 UTC, kenshi84 commented
@cdcseacave Thanks for your feedback, modified the patch accordingly.

2023-03-17 08:47 UTC, merged